# Generated by Django 5.0.3 on 2024-10-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.IntegerField()),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
